### ISSUE TITLE
GRIDSS docker

### ISSUE THREAD

**Issue by d-cameron** [papaemmelab/docker-gridss#1]
Hello, I found this repository via a google search.

GRIDSS releases now include a docker container on dockerhub (gridss/gridss). The latest release also includes a wrapper shell script so there's no longer any need to worry about updating your scripts when the optimal JVM parameters are changed between releases. Additionally, the StructuralVariantAnnotation R package used to simplify downstream analysis is now on BioConductor.

If you want to build the GRIDSS docker locally, the Dockerfile can be found in the https://github.com/PapenfussLab/gridss/tree/master/docker directory. 

Let me know if there's anything else I can do to improve the user experience.

**Comment by juanesarango** [comment]
Thanks @d-cameron that's very useful
